### ISSUE TITLE
Unable to upload in the UI KIT and Components folder

### ISSUE THREAD

**Issue by Nuel0** [IndianOpenSourceFoundation/iosf-design#3]

**Comment by GouravSardana** [comment]
No, you have the access to upload. You don't push directly to this. Fork this repo and upload your changes. Send us a pull request. We will review it

**Comment by Nuel0** [comment]
I've sent a pull request already

**Comment by GouravSardana** [comment]
If you see, I accepted that and structure it in the right folder

**Comment by tory-brown** [comment]
if it is settled, this issue should be closed.

**Comment by GouravSardana** [comment]
Closing this issue.
