### ISSUE TITLE
LICENSE Missing

### ISSUE THREAD

**Issue by gaushikmr** [IndianOpenSourceFoundation/iosf-design#7]

**Comment by GouravSardana** [comment]
Hey @gaushikmr , 
If you wish to contribute, you can add GPL3 for this design-track

**Comment by GouravSardana** [comment]
Thanks @gaushikmr .

You can also join our slack community [here](https://join.slack.com/t/iosf-india/shared_invite/zt-gt1emqhs-oSR5uUA89pfdAPMmdlB79A)
